# Generated by Django 3.1.2 on 2021-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.ImageField(default=None, upload_to='qrcodes/'),
        ),
    ]
