# Generated by Django 3.1.2 on 2021-01-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='code',
        ),
        migrations.CreateModel(
            name='TicketQrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ImageField(upload_to='qrcodes/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
        ),
    ]
