# Generated by Django 3.1.2 on 2021-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210113_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.ImageField(default=None, null=True, upload_to='qrcodes/'),
        ),
    ]
