# Generated by Django 3.1.2 on 2021-01-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='code',
        ),
    ]
