# Generated by Django 3.1.2 on 2021-01-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.ImageField(default=None, null=True, upload_to='qrcodes/'),
        ),
    ]
