# Generated by Django 3.1.2 on 2021-01-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketqrcode',
            name='code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
