# Generated by Django 3.1.2 on 2021-01-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20210113_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='code',
        ),
        migrations.AlterField(
            model_name='ticketqrcode',
            name='code',
            field=models.ImageField(blank=True, default=None, upload_to='qrcodes/'),
        ),
    ]
