# Generated by Django 3.1.2 on 2021-01-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20210114_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.ImageField(default=None, null=True, upload_to='qrcodes/'),
        ),
        migrations.DeleteModel(
            name='TicketQrCode',
        ),
    ]
