# Generated by Django 3.1.2 on 2021-01-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20210114_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.ImageField(blank=True, default=None, upload_to='qrcodes/'),
        ),
    ]
